["protostar.config"]
protostar_version = "0.2.6"

["protostar.project"]
libs_path = "lib"


["protostar.shared_command_configs"]
cairo_path = ["src", "lib/cairo_contracts/src"]

["protostar.contracts"]
my_contract = ["src/v2.cairo"]
proxy = [ "./lib/cairo_contracts/src/openzeppelin/upgrades/presets/Proxy.cairo" ]
my_contract_migration = ["src/my_contract_migration.cairo"]

[profile.devnet.protostar.deploy]
gateway_url="http://127.0.0.1:5050/"
feeder_gateway_url="http://127.0.0.1:5050/"
network_opt="--gateway_url http://127.0.0.1:5050 --feeder_gateway_url http://127.0.0.1:5050"

[profile.testnet.protostar.deploy]
network="alpha-goerli"
network_opt="--network alpha-goerli"
